USEID-589/tidy up documentation
digitalservicebund/useid-architecture pull request #10
Opened 2022-10-17 08:45 UTC by mpanne

Cleanup documentation:

- Remove sequence diagram for desktop flows
- Add sequence diagram for Magnus mobile only flow
- Update Magnus integration guide to fit for mobile only flow

2022-10-17 12:02 UTC, code28 requested changes
Just tiny comments, otherwise: 👍

2022-10-17 14:44 UTC, hannesschaletzky approved these changes

2022-10-18 14:25 UTC, mpanne commented on doc/eID/eid-integration-magnus.md
>  # UseID Integration
For now we will leave it as is and use "UseID". See [discussion in Slack](https://digitalservicebund.slack.com/archives/C0314PBC8U8/p1666086966535679).

2022-10-18 14:32 UTC, mpanne commented on doc/eID/eid-integration-magnus.md
> +> The eService usually presents a link to the user which points to the eID client application (e.g. AusweisApp2, BundesIdent) including the tcTokenURL as a query parameter. With UseID, this is handle
Added something.

2022-10-18 14:32 UTC, mpanne commented on doc/eID/eid-integration-magnus.md
>  The user is returned to the `refreshAddress` of the eService, which is provided in the TC token, on the device displaying the widget.
Good catch.

2022-10-19 05:33 UTC, code28 approved these changes

2022-10-19 06:22 UTC, merged