USEID-506: Add ADR 0008 soap over saml
digitalservicebund/useid-architecture pull request #15
Opened 2022-12-21 15:22 UTC by hannesschaletzky

[Ticket](https://digitalservicebund.atlassian.net/browse/USEID-506) 

Write an ADR outlining the pros and cons of SOAP and SAML as an eid server integration and write down the reasons for our decision to go with SOAP

2022-12-21 15:45 UTC, pgurusinga commented on doc/adr/0008-soap-over-saml.md
> +- SAOP (Simple Object Access Protocol)
```suggestion
- SOAP (Simple Object Access Protocol)
```

2022-12-22 07:47 UTC, phuesler commented on doc/adr/0008-soap-over-saml.md
> +We need to decide for one interface.<br>
```suggestion
We need to decide for one interface.
```

2022-12-22 13:00 UTC, code28 requested changes
Looks good! Just needs the decision, I'd say :)

2022-12-22 13:00 UTC, code28 commented on doc/adr/0008-soap-over-saml.md
> +We create the SOAP signature certificates and implement a proxy behaviour from the eID-Server to the eService, passing the ID data without storing it at any point.
For me, this could have a stronger connection to "us", e.g. "We implement [...]. We won't store data at any point."

2022-12-27 11:33 UTC, pgurusinga commented on doc/adr/0008-soap-over-saml.md
> +(Flow charts for both approaches of the eID-Server implementation can be found in the _Integrationshandbuch für den eID-Service der D-Trust, Version 2.0.0_)
We can find charts for both e.g
![image](https://user-images.githubusercontent.com/9930966/209660568-426ac6ef-2567-4ec5-94b6-c74a84d721f8.png)

2.2 Communication model — page 13 https://www.bsi.bund.de/SharedDocs/Downloads/DE/BSI/Publikationen/TechnischeRichtlinien/TR03130/TR-03130_TR-eID-Server_Part1.pdf?__blob=publicationFile&v=3

2022-12-27 11:45 UTC, pgurusinga commented
@hannesschaletzky it would be great if we could align the commit message

2022-12-30 10:19 UTC, merged